# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('working_location', models.CharField(choices=[('BO', 'Box Office'), ('MD', 'Main Desk'), ('FC', 'Fitness Center'), ('EC', 'Equipment Checkout')], default='MD', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=75)),
                ('weekly_hours', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.User'),
        ),
    ]
