# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20160710_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='month',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='JAN', max_length=3),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
