# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_shift_type_of_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.User')),
            ],
        ),
    ]
