# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_news_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='release_reason',
            field=models.TextField(default='Blank'),
        ),
    ]
