# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_shift_release_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='type_of_shift_release',
            field=models.CharField(choices=[('null', 'null'), ('PS', 'Permanent shift release'), ('TS', 'Temporary shift release')], default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='shift',
            name='working_location',
            field=models.CharField(choices=[('Box Office', 'Box Office'), ('Main Desk', 'Main Desk'), ('Fitness Center', 'Fitness Center'), ('Equipment Checkout', 'Equipment Checkout')], default='Main Desk', max_length=20),
        ),
    ]
