# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20160710_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='type_of_shift',
            field=models.CharField(choices=[('PS', 'Permanent shift'), ('TS', 'Temporary shift')], default='PS', max_length=20),
        ),
    ]
